services:
  app:
    build: .
    container_name: ${APP_NAME}-app
    restart: always
    #ports:
    #  - "3000:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/.env:/app/server/.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3001"

networks:
  web:
    external: true